version: "3"

services:
  db:
    container_name: gogrpc
    image: postgres:10.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./up.sql:/docker-entrypoint-initdb.d/1.sql
